export enum PatchableMethods {
    GET_CLIENT_QUESTS = "getClientQuests",
    PLAYER_LEVEL_FULFILLS_QUEST_REQUIREMENT = "playerLevelFulfillsQuestRequirement",
    ACCEPT_QUEST = "acceptQuest",
    ACCEPT_REPEATABLE_QUEST = "acceptRepeatableQuest",
    CREATE_ACCEPTED_QUEST_CLIENT_RESPONSE = "createAcceptedQuestClientResponse",
    GET_REPEATABLE_QUEST_FROM_PROFILE = "getRepeatableQuestFromProfile",
    COMPLETE_QUEST = "completeQuest",
    GET_QUESTS_FAILED_BY_COMPLETING_QUEST = "getQuestsFailedByCompletingQuest",
    REMOVE_QUEST_FROM_SCAV_PROFILE = "removeQuestFromScavProfile",
    GET_QUESTS_WITH_DIFFERENT_STATUSES = "getQuestsWithDifferentStatuses",
    SEND_SUCCESS_DIALOG_MESSAGE_ON_QUEST_COMPLETE = "sendSuccessDialogMessageOnQuestComplete",
    ADD_TIME_LOCKED_QUESTS_TO_PROFILE = "addTimeLockedQuestsToProfile",
    FAIL_QUESTS = "failQuests",
    HANDOVER_QUEST = "handoverQuest",
    SHOW_REPEATABLE_QUEST_INVALID_CONDITION_ERROR = "showRepeatableQuestInvalidConditionError",
    SHOW_QUEST_ITEM_HANDOVER_MATCH_ERROR = "showQuestItemHandoverMatchError",
    UPDATE_PROFILE_TASK_CONDITION_COUNTER_VALUE = "updateProfileTaskConditionCounterValue",
    FAIL_QUEST = "failQuest"
}
